set(__QT_DEPLOY_TARGET_INDICamRecorder_FILE /Users/artemzubko/Projects/indi-camrecorder/buld/INDICamRecorder.app/Contents/MacOS/INDICamRecorder)
set(__QT_DEPLOY_TARGET_INDICamRecorder_TYPE EXECUTABLE)
